# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isConnected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
