# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_auto_20170627_0714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='TLContact',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='TLUser',
        ),
    ]
